<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMsZvIJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMsZvIJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMsZvIJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMsZvIJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTMsZvIJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TMsZvIJ',
    'container.build_id' => '85f0cb14',
    'container.build_time' => 1553158374,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMsZvIJ');
